# This file will probably grow as we add and customize exceptions.
# It will be a good idea to split it into multiple files.
class ExternalServiceException(Exception): ...


class UserNotFoundException(Exception): ...


class PropertyNotFoundException(Exception): ...


class PreferencesNotFoundException(Exception): ...


class NotificationNotFoundException(Exception): ...


class NotificationInsertionException(Exception): ...


class NotificationDispatchException(Exception): ...
