"""init

Revision ID: aafbfc6a2ed2
Revises:
Create Date: 2025-03-05 14:47:53.656165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aafbfc6a2ed2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("property_id", sa.String(), nullable=False),
        sa.Column("scheduled_time_utc", sa.DateTime(), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=True),
        sa.Column(
            "service_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum("email", "sms", name="notification_type_enum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preferences",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("sms_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "property_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "email_notification_detail",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("html_body", sa.String(), nullable=False),
        sa.Column("text_body", sa.String(), nullable=False),
        sa.Column("from_email", sa.String(), nullable=True),
        sa.Column("to_email", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notification.id"],
        ),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    op.create_table(
        "sms_notification_detail",
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("to_phone_number", sa.String(), nullable=False),
        sa.Column("from_phone_number", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notification.id"],
        ),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sms_notification_detail")
    op.drop_table("email_notification_detail")
    op.drop_table("preferences")
    op.drop_table("notification")
    # ### end Alembic commands ###
